name: release database
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: create env
      run: 'POSTGRES_PRISMA_URL="${{ secrets.POSTGRES_PRISMA_URL}}"' > .env
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r harvester/requirements.txt
        prisma generate
    - name: update db
      run: python harvester
